apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: general-intentions
  namespace: app
spec:
  destination:
    name: general
  sources:
    - name: frontend
      action: allow
    - name: "*"
      action: deny
